services:
  kscu-web-server:
    build: .
    container_name: kscu-web-server
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
      - ./temp_recordings:/tmp
    env_file:
      - .env
    ports:
      - "8000:8000"