version: '3.8'

services:
  kscu-app:
    build: .
    container_name: kscu-app
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
    env_file:
      - .env

  kscu-proxy:
    image: nginx:alpine
    container_name: kscu-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./temp_recordings:/tmp
    depends_on:
      - kscu-app