[project]
name = "dj-schedule-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.28",
    "datetime>=6.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.128.0",
    "itsdangerous>=2.2.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.12",
    "requests>=2.32.5",
    "schedule>=1.2.2",
    "sse-starlette>=3.2.0",
    "yagmail>=0.15.293",
]
